# Generated by Django 6.0.3 on 2026-04-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('accidente', 'Accidente'), ('casi_accidente', 'Casi accidente'), ('condicion_insegura', 'Condición insegura')], max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
