# Generated by Django 6.0.4 on 2026-05-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='bajo', max_length=10),
        ),
    ]
