# Generated by Django 6.0.4 on 2026-06-29 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_incidente_riesgo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='acciones_correctivas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Critico')], default='bajo', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipo',
            field=models.CharField(choices=[('accidente', 'Accidente'), ('casi_accidente', 'Casi accidente'), ('condicion_insegura', 'Condicion insegura')], max_length=20),
        ),
    ]
