# Generated by Django 6.0.4 on 2026-07-07 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_incidente_acciones_correctivas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='incidentes/evidencias/', verbose_name='Evidencia fotográfica'),
        ),
        migrations.CreateModel(
            name='HistorialIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='incidentes.incidente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
