# Generated by Django 6.0.4 on 2026-07-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0004_incidente_evidencia_historialincidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='consecuencias',
            field=models.TextField(blank=True, verbose_name='Consecuencias del incidente'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones adicionales'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='baja', max_length=15, verbose_name='Prioridad'),
        ),
    ]
